---
- import_playbook: ../../include_vars.yml

- name: Cleanup and Delete all Infrastructure
  environment:
    AZURE_CLIENT_ID: "{{azure_service_principal}}"
    AZURE_TENANT: "{{azure_tenant}}"
    AZURE_SECRET: "{{azure_password}}"
    AZURE_SUBSCRIPTION_ID: "{{azure_subscription_id}}"
    AZURE_CONFIG_DIR: "{{ output_dir }}/.azure-{{project_tag}}"
    PATH: '{{ output_dir }}:/bin:/usr/bin:/usr/local/bin'
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
