---
- name: Step 000 Post Software
  hosts: localhost
  connection: local
  become: false
  tags:
    - step001
    - post_software
  tasks:
    - debug:
        msg: "Step 000 Post Software - Starting"

- name: Step 002 Post Software
  hosts: localhost
  connection: local
  become: false
  tags:
    - step001
    - post_software
  tasks:
    - debug:
        msg: "Step 002 Post Software - Completed"

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
